# Generated by Django 3.2 on 2023-11-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(verbose_name='updated_date')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('image', models.ImageField(upload_to='course_category', verbose_name='image')),
                ('color', models.CharField(choices=[('edu_cat_2 cat-1', 'edu_cat_2 cat-1'), ('edu_cat_2 cat-2', 'edu_cat_2 cat-2'), ('edu_cat_2 cat-3', 'edu_cat_2 cat-3'), ('edu_cat_2 cat-4', 'edu_cat_2 cat-4'), ('edu_cat_2 cat-10', 'edu_cat_2 cat-10'), ('edu_cat_2 cat-6', 'edu_cat_2 cat-6'), ('edu_cat_2 cat-7', 'edu_cat_2 cat-7'), ('edu_cat_2 cat-8', 'edu_cat_2 cat-8'), ('edu_cat_2 cat-9', 'edu_cat_2 cat-9')], max_length=100, verbose_name='COLOR')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
