# Generated by Django 4.2.7 on 2023-11-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created_date"
                    ),
                ),
                ("updated_date", models.DateTimeField(verbose_name="updated_date")),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                ("intro", models.CharField(max_length=50, verbose_name="intro")),
                ("description", models.TextField(verbose_name="description")),
            ],
            options={
                "verbose_name": "courses",
                "verbose_name_plural": "courses",
                "db_table": "course",
            },
        ),
    ]
