# Generated by Django 4.2.7 on 2023-11-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0004_course_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("begginer", "begginer"),
                    ("intermediate", "intermediate"),
                    ("advance", "advance"),
                ],
                default="begginer",
                max_length=50,
                verbose_name="level",
            ),
        ),
    ]
