# Generated by Django 4.2 on 2023-12-14 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='education.course'),
        ),
        migrations.AlterModelTable(
            name='section',
            table='section',
        ),
    ]
