# Generated by Django 4.2 on 2023-12-14 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_section_course_alter_section_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(verbose_name='updated_date')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='education.section')),
            ],
            options={
                'db_table': 'lesson',
            },
        ),
    ]
